### PR TITLE
change GeoViews to geoviews (import name)

### PR DESCRIPTION
**Pull request by raybellwaves**

### CODE REVIEW

**Comment by maximlt** [comment]
Thanks! Why did you remove `pyproj`?

**Comment by raybellwaves** [comment]
> Thanks! Why did you remove `pyproj`?

I put it in the commit message but show have explained here: it's installed with cartopy

**Comment by maximlt** [comment]
Indeed I missed that. I actually added pyproj recently, the fact that cartopy depends on pyproj is an implementation detail. Sure this is not meant to change any time soon, but well, I prefer to be explicit in these cases.

If that's fine for you I'll add it back?

**Comment by raybellwaves** [comment]
np. just added it back in

**Comment by maximlt** [comment]
Great thanks!

**Pull request merged**
