### PR TITLE
MAINT: Drop support for py2.7, min supported version is py3.6 now

### PR DESCRIPTION
**Pull request by MridulS**
I went a bit aggressive with dropping older python version support 😅
This PR makes 3.7 the min supported version.

Is this reasonable? 

The test pipelines do not work with 3.8, 3.9 and 3.10 (https://github.com/holoviz/hvplot/pull/701) but I think the code itself should work.

### CODE REVIEW

**Comment by jlstevens** [comment]
> Is this reasonable?

Thanks for dropping Python 2 support (finally!)

As for dropping 3.6 right now, I do think that is too aggressive. I do know various projects are also aggressively dropping support within the 3.x series but I do think there are still plenty of users still using python 3.6...

**Comment by MridulS** [comment]
The syntax should be fine with 3.6 too.

**Comment by jlstevens** [comment]
Thanks!

Once the tests pass, I think it looks good to merge!

**Comment by maximlt** [comment]
Great thanks for updating it @MridulS , merging!

**Pull request merged**
