### PR TITLE
MAINT: Add support for planar layout from NX

### PR DESCRIPTION
**Pull request by MridulS**
Added support for [nx.draw_planar convenience function](https://networkx.org/documentation/stable/reference/generated/networkx.drawing.nx_pylab.draw_planar.html) and an example to the User guide.

Wasn't sure how to test this, let me know if I anything else is required :)

### CODE REVIEW

**Comment by maximlt** [comment]
Hey thanks @MridulS for the PR!

I don't think it's documented anywhere (while it should!) but there's a little script we run on a notebook before committing any change to strip its metadata. You need to have `jq` installed on your system:

```bash
#!/bin/bash

jq --sort-keys --indent 1 \
    '
    (.cells[] | select(has("outputs")) | .outputs) = []
    | (.cells[] | select(has("execution_count")) | .execution_count) = null
    | .metadata = {"language_info": {"name":"python", "pygments_lexer": "ipython3"}}
    | .cells[].metadata = {}
    | del(.cells[].id)
    ' "$1" > /tmp/$(basename $1) && cat /tmp/$(basename $1) > "$1"
```

Otherwise your PR looks good to me.

**Review by jbednar — APPROVED** [review]
Looks good, once the metadata is cleared and the tests pass. Thanks!

**Comment by MridulS** [comment]
The 2.7 failure was unrelated from this change, should be fixed by https://github.com/holoviz/hvplot/pull/700/commits/e82b953dab74d9f162392d13d7b36274e9a9fb9c .

**Comment by MridulS** [comment]
https://github.com/holoviz/hvplot/pull/651 has a couple of py3 specific syntax (numeric underscores and f strings).
Is it time to drop py2.7 support?

**Comment by philippjfr** [comment]
I'd be happy to drop py2.7 as part of the 0.8 release tbh.

**Comment by MridulS** [comment]
This should be ready to merge then :)

**Comment by philippjfr** [comment]
Thanks @MridulS!

**Pull request merged**
