### PR TITLE
Use nbval and nbqa for managing notebooks

### PR DESCRIPTION
**Pull request by MridulS**
Update: Moved to use the `flake8` linter instead, it respects `# noqa`and it's passing the CI without complaining. For`nbsmoke_skip_run`, I've used a `pytest` setting `ignore-glob`.

 ----------------------------------------------------
Currently the `pylint` module for `nbqa` complains a lot as `pylint` checks for many more things as compared to `pyflakes`.
We can also turn on other linters like `black`, `isort`, `pyupgrade` for the notebooks.

One thing that doesn't directly translate from `nbsmoke` to `nbval` is the the `nbsmoke_skip_run` pytest setting. We can use the explicit `ignore` while executing `pytest --nbval-lax` but it won't accept regex (I think?)

### CODE REVIEW

**Comment by maximlt** [comment]
@MridulS could you please push an empty commit to trigger the CI?

**Comment by MridulS** [comment]
Hmm, I am getting a "Startup failure" while running the job on Github Actions https://github.com/holoviz/hvplot/actions/runs/2027074647. Interesting, I haven't seen this before.

**Comment by maximlt** [comment]
I've never seen that too and the error reported at line 67 seems just wrong, there's no `cache` identifier in this workflow. Do you want me to open a new PR with your changes to see how that goes?

**Comment by MridulS** [comment]
yeah sure! please do that.

**Pull request closed without merging**
