### PR TITLE
Remove auto setting data aspect for geo

### PR DESCRIPTION
**Pull request by ahuang11**
This setting actually caused issues

Before:

https://github.com/holoviz/hvplot/assets/15331990/d4004c88-f90c-42fa-a57d-34b32ae46a4a

After:

https://github.com/holoviz/hvplot/assets/15331990/0ba3b2e0-647c-4591-874d-ae54cd166b73

Closes https://github.com/holoviz/hvplot/issues/1105

### CODE REVIEW

**Review by maximlt — COMMENTED** [review]
Isn't this change working around a bug in HoloViews? It's a pretty bad bug, but it seems like the change is removing a requested feature (https://github.com/holoviz/hvplot/issues/192). We can decide the feature is not worth it, but it needs to be explicit and we need to assess the full extent of its effects.

**Comment by ahuang11** [comment]
I suppose I could dig deeper and see if the underlying bug can be fixed; if not I'd still say this PR is worth merging because it's practically unusable right now.

**Comment by ahuang11** [comment]
I suppose it's not a geo/hvplot specific issue, rather, a HoloViews issue.

Going to close this and if I figure it out, open a PR in holoviews.

```
import holoviews as hv
from holoviews.operation.datashader import rasterize
hv.extension("bokeh")

rasterize(hv.Curve([0, 1, 2])).opts(data_aspect=1)
```

**Comment by ahuang11** [comment]
Resolving here instead: https://github.com/holoviz/holoviews/pull/6189

**Pull request closed without merging**
