### PR TITLE
Fix minor issues in explorer

### PR DESCRIPTION
**Pull request by ahuang11**
Tweaks to labels, placeholders, margins, layout of explorer, based on the minor issues listed here:
https://github.com/holoviz/hvplot/issues/1190

image

### CODE REVIEW

**Comment by maximlt** [comment]
Why has the status bar been moved to the top? I'm much more used to having a status bar at the bottom, like in the Perspective viewer or in QGIS. That's where it usually is apparently:
image

**Comment by ahuang11** [comment]
I personally do not think the `Live Update` should be called "Status Bar"

Also, if it's on the bottom, the plot will push it out of view.

image

**Comment by maximlt** [comment]
Yes probably status bar isn't the right word for that, although I've seen status bar used for components that do provide some control (like in [QGIS](https://docs.qgis.org/3.28/en/docs/user_manual/introduction/qgis_gui.html#status-bar)).

It's easy to see though that we can add more of this kind of tools (reset, export, ...) and indicators (mouse position?), and I guess we should try to have them fit all in the same horizontal bar, so pick between top or bottom location. I think I prefer at the bottom as that's not the first thing users should see and click on, however I'm no UI/UX professional so I may just be plain wrong.

> Also, if it's on the bottom, the plot will push it out of view

That's certainly the crux of the problem, in that we don't have very good control over the plot height, and even the Tab layout height that right now is as tall as its tallest item. There's a bit of a tension between allowing the users to set the plot dimensions (aka the explorer as a plot builder/editor/wizard) and giving them the best plot for them to explore their data (aka the explorer as the explorer!).

**Comment by maximlt** [comment]
Ok at the top is fine.

**Comment by ahuang11** [comment]
Can we merge this then or do you need more time to review it?

**Comment by maximlt** [comment]
I'll review it later.

**Comment by maximlt** [comment]
LGTM!

I still think the status/control bar is a bit in a weird place and looks to big for what it is, I don't want to block to PR for too long though as others depend on it and there may be conflicts. Hopefully one day we'll be supported by UI/UX engineers for this sort of design work!

image

**Pull request merged**
