### PR TITLE
Set interactive function to lazy to avoid calling it twice

### PR DESCRIPTION
**Pull request by Hoxbro**
Splits up the fixes in #768 as this change is unrelated to the warning.  

I have commented out part of the test related to the changes in #768, that PR should uncomment those lines.

### CODE REVIEW

**Comment by Hoxbro** [comment]
The failing tests were related to a data file no longer being at the https://github.com/mapbox/rasterio/raw/master/tests/data/RGB.byte.tif, but here https://github.com/rasterio/rasterio/raw/main/tests/data/RGB.byte.tif. A change from master --> main. 

I did add the data file to the commit instead of using the URL as before to avoid having a problem like this in the future. But I'm wondering if this could affect the package size and if I should go back to using the URL.

**Comment by jbednar** [comment]
1.67MB does seem like a lot just to get an example image, but I'm not sure what fraction of the overall package that represents.

**Comment by Hoxbro** [comment]
What if I exclude the file in `MANIFEST.in`? I can then, in a follow-up PR, change the path to a hvplot URL. 

That way, we have complete control over the file and the data in it, and people will still be able to run the test locally.

**Comment by MarcSkovMadsen** [comment]
With pyscript and python

**Comment by philippjfr** [comment]
Can we use a more minimal tif file?

**Comment by Hoxbro** [comment]
> Can we use a more minimal tif file?

Properly, but I don't know how comprehensive it will be to create and update the code. I will change it back to a URL and make an issue about updating the file testing.

**Comment by maximlt** [comment]
This looks good to me, thanks!

**Pull request merged**
